### PR TITLE
Upgrade to ddtrace v 1.1

### PR DESCRIPTION
**Pull request by ccuadrado-assurance**
Need to refactor due to breaking changes going from 0.x to 1.x, followed guide here:
https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md

### Types of Changes

- Bug fix.

### Testing

- [x] I added tests for my changes.
- [x] I tested my changes locally.
- [ ] I tested my changes in staging.
- [ ] I tested my changes in production.

### CODE REVIEW

**Comment by ioquatix** [comment]
This looks great to me and I apologise for not replying sooner, but I did actually request @ivoanjo to take a look because something is broken on Ruby head. Obviously not our problem, but none the less an issue we might want to draw attention to.

**Comment by ioquatix** [comment]
See https://github.com/DataDog/dd-trace-rb/issues/2065 fix https://github.com/DataDog/dd-trace-rb/pull/2066

**Comment by ccuadrado-assurance** [comment]
@ioquatix Can we override the ruby head check and integrate this PR or would you prefer to edit the github action with the right environment variable to make sure everything is passing first? This is blocking some work I'm doing upstream integrating Datadog with an application to test ASM as it requires dtrace v1.1 for a specific logger gem we use.

**Comment by ivoanjo** [comment]
Thanks y'all for the work and for working around the issue 🙇

**Comment by ioquatix** [comment]
@ccuadrado-assurance Okay, I've released v0.2.0

**Pull request merged**
